version: "3.7"
services:
  backend:
    image: python:3.7
    command: ["bash", "/app/backend/scripts/run-dev.sh"]
    volumes:
      - ./backend:/app/backend
      - ./backend/venv:/app/backend/venv
      - backend_data:/root/uploads
    environment:
      ADMIN_USERNAME: "aijam"
      ADMIN_PASSWORD: "aijam"
      DATABASE_URL: "mysql+pymysql://audino:audino@mysql/audino?charset=utf8mb4"
      FLASK_APP: "app.py"
      FLASK_DEBUG: 1
      FLASK_ENV: "development"
      JWT_SECRET_KEY: "secretkey"
      JWT_REDIS_STORE_URL: "redis://:audino@redis:6379/0"
    ports:
      - 5000:5000
    depends_on:
      - mysql
      - redis
    networks:
      - backend-network
      - frontend-network

  frontend:
    image: node:14.18.1
    command: ["bash", "/app/frontend/scripts/run-dev.sh"]
    volumes:
      - ./frontend:/app/frontend
      - ./frontend/node_modules:/app/frontend/node_modules
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - frontend-network

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/mysql
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "audino"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "audino"
      MYSQL_PASSWORD: "audino"
    command: --init-file=/mysql/create_database.sql --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    networks:
      - backend-network

  redis:
    build: ./redis
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: "audino"
    networks:
      - backend-network

volumes:
  mysql_data: 
    driver_opts:
      type: none
      device: ./data/mysql
      o: bind
  redis_data: 
    driver_opts:
      type: none
      device: ./data/redis
      o: bind
  backend_data:
    driver_opts:
      type: none
      device: ./data/backend
      o: bind

networks:
  backend-network:
  frontend-network:
